const appImages = {
  apple_logo: require('../assets/images/apple-logo.png'),
  login_logo: require('../assets/images/loginImage.png'),
  fb_logo: require('../assets/images/facebook-circular-logo.png'),
  google_logo: require('../assets/images/google_logo.png'),
  player_male: require('../assets/images/player_male.png'),
  player_female: require('../assets/images/female_onboard_Icon.png'),
  dropdown: require('../assets/chevrondown5.png'),
  fileEnvelope: require('../assets/fileEnvelope.png'),
  court: require('../assets/court.png'),
  moreVertical: require('../assets/images/more-vertical.png'),
  crown: require('../assets/images/crown.png'),
  yellowCheckBadge: require('../assets/images/lineUpPremiumCheck.png'),
  playerRequestIcon: require('../assets/images/playerprofileIcon.png'),
  playerCompareIcon: require('../assets/images/playerprofileIcon2.png'),
  defaultAvatarImage: require('../assets/images/AvatarImage.png'),
  placeHolderPhotoIdBorder: require('../assets/images/placeHolder_photoid_border.png'),
  placeholderPhotoId: require('../assets/images/Placeholder_PhotoId.png'),
  certificateCoaching: require('../assets/images/certificate_coaching.png'),
  coachOnboardingIcon: require('../assets/images/coach_onboard_icon.png'),
  practiceCardImage: require('../assets/practice_court.png'),
  playerPlaying: require('../assets/images/player_playing2.png'),
  recoderPlaceholder: require('../assets/images/recorder_placeholder.png'),
  checkCircle: require('../assets/images/CheckCircle.png'),
  // backIcon: require('../assets/images/back_ico.png'),
  // maleProfile: require('../assets/images/maleProfile.jpg'),
  // femaleProfile: require('../assets/images/FemalePlayerProfile.jpg'),
  // maleAtheletic: require('../assets/images/MaleAthletic.jpg'),
  // maleDefender: require('../assets/images/MaleDefender.jpg'),
  // malePlayMaker: require('../assets/images/MalePlaymaker.webp'),
  // maleShooter: require('../assets/images/MaleShooter.jpg'),
  // maleAllRound: require('../assets/images/MaleAllAround.jpg'),
  // femaleDefender: require('../assets/images/FemaleDefender.jpg'),
  // femalePlayMaker: require('../assets/images/FemalePlaymaker.jpg'),
  // femaleShooter: require('../assets/images/FemaleShooter.jpg'),
  // femaleSlasher: require('../assets/images/FemaleSlasher.jpg'),
};

export { appImages };
