const appImages = {
  apple_logo: require('../assets/images/apple-logo.png'),
  login_logo: require('../assets/images/loginImage.png'),
  fb_logo: require('../assets/images/facebook-circular-logo.png'),
  google_logo: require('../assets/images/google_logo.png'),
  player_male: require('../assets/images/player_male.png'),
  player_female: require('../assets/images/female_onboard_Icon.png'),
  dropdown: require('../assets/chevrondown5.png'),
  fileEnvelope: require('../assets/fileEnvelope.png'),
  court: require('../assets/court.png'),
  moreVertical: require('../assets/images/more-vertical.png'),
  // backIcon: require('../assets/images/back_ico.png'),
  // maleProfile: require('../assets/images/maleProfile.jpg'),
  // femaleProfile: require('../assets/images/FemalePlayerProfile.jpg'),
  // maleAtheletic: require('../assets/images/MaleAthletic.jpg'),
  // maleDefender: require('../assets/images/MaleDefender.jpg'),
  // malePlayMaker: require('../assets/images/MalePlaymaker.webp'),
  // maleShooter: require('../assets/images/MaleShooter.jpg'),
  // maleAllRound: require('../assets/images/MaleAllAround.jpg'),
  // femaleDefender: require('../assets/images/FemaleDefender.jpg'),
  // femalePlayMaker: require('../assets/images/FemalePlaymaker.jpg'),
  // femaleShooter: require('../assets/images/FemaleShooter.jpg'),
  // femaleSlasher: require('../assets/images/FemaleSlasher.jpg'),
};

export { appImages };
